### ISSUE TITLE
Logg error if file already exits

### ISSUE THREAD

**Issue by hung135** [hung135/file_router#13]
Traceback (most recent call last):
  File "tests/test_file_router.py", line 70, in test_03_move_files
    pio.outgoing.move_files(pio.incoming.files)
  File "/workspace/scripts/projectio.py", line 65, in move_files
    [shutil.move(f, self.path) for f in files]
  File "/workspace/scripts/projectio.py", line 65, in <listcomp>
    [shutil.move(f, self.path) for f in files]
  File "/usr/local/lib/python3.7/shutil.py", line 561, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/workspace/outgoing/project2/.' already exists

**Comment by hung135** [comment]
looks like you storing the path (".")  as an entry in your "path" list and trying to move that also:

/home/dtdata/transfer/connect_direct/frb/download/Porro_numquam_est.xls --------------
/home/dtdata/transfer/connect_direct/frb/download/Eius_quiquia.db --------------
/home/dtdata/transfer/connect_direct/frb/download/Dolorem_numquam_quiquia.xls --------------
/home/dtdata/transfer/connect_direct/frb/download/Amet_tempora.xls --------------
/home/dtdata/transfer/connect_direct/frb/download/Ut_dolor_adipisci.db --------------
/home/dtdata/transfer/connect_direct/frb/download/Aliquam_consectetur_neque.db --------------
/home/dtdata/transfer/connect_direct/frb/download/Consectetur_etincidunt.db --------------
/home/dtdata/transfer/connect_direct/frb/download/Magnam_sit.xls --------------
/home/dtdata/transfer/connect_direct/frb/download/Ipsum_non.xls --------------
/home/dtdata/transfer/connect_direct/frb/download/Sit_tempora_dolore.txt --------------
/home/dtdata/transfer/connect_direct/frb/download/Adipisci_tempora_tempora.db --------------
/home/dtdata/transfer/connect_direct/frb/download/Quisquam_modi_est.txt --------------
/home/dtdata/transfer/connect_direct/frb/download/Quisquam_dolor.txt --------------
/home/dtdata/transfer/connect_direct/frb/download/Eius_dolorem.db --------------
/home/dtdata/transfer/connect_direct/frb/download/. --------------

**Comment by hung135** [comment]
class Incoming:
    def __init__(self, project, **config):
        self.__dict__.update(config)
        self.project = project
       #take out the "." entry from this walk as it errors out later on
        self.files = self._walk_files()
        self.mappings = []

**Comment by hung135** [comment]
def _walk_files(self):
        if hasattr(self, "file_pathern"):
            paths = []
            for t in self.file_pathern:


pathern....-->pattern

**Comment by redspart** [comment]
- "file_pathern" has been updated to "file_pattern"
- Took out the dot directory 
- Added logging fc0328f125b22490f18e4ab032ba5895c6af3503
