### ISSUE TITLE
file_data_extract does not extract value

### ISSUE THREAD

**Issue by hung135** [hung135/file_router#18]
\d\d\d\d should extract 1992 from incoming path.
it doesn't seem to be doing that.

**Comment by hung135** [comment]
partially working /xxxx/2011/2001/xxxx.xls
will pick up 2011 not 2001...

**Comment by redspart** [comment]
I am not seeing this behavior. Responded to a code change; https://github.com/hung135/file_router/commit/a2b209046299bce8039f4dbf5547454fa2331c05#r34192342
