### ISSUE TITLE
Enhance Github release features

### ISSUE THREAD

**Issue by hung135** [hung135/file_router#47]
- [x] Feature to print out all release tag ordered from newest to oldest
- [x] Feature to push an asset file with a new release tag, if release tag already exists abort and warn accordingly, if release tag doesn't exist create it and add the file to the release tag
- [x] Feature to just add a file to a release tag that already exists

**Comment by redspart** [comment]
Done e680d5c492bf30962b746d45b47ebf683fbdb793
@hung135

**Comment by redspart** [comment]
Reopened: want to create a hook that gets the latest tag's release and downloads that file.

@hung135 done here: 197ba61f2a85fad6b504c4fdd4a91622974ae470

Added `-dl <tag> -o <output dir>` and `-gl (prints latest tag)`; for now you will still need the options `-k -r`
